### ISSUE TITLE
no input apart zooming in-out

### ISSUE THREAD

**Issue by Paolo-Oliverio** [Fattorino/ImNodeFlow#20] opened 2024-04-02 17:42 UTC
tested your simple example but i cannot move nodes around or make connections I can just zoom in and any other input is ignored.

the fact that zooming works makes me guess my imgui implementation is ok as it also works correctly if I make normal imgui widgets.

I probably I forgot to initialize something... does it ring some bells?

this is the nodeflow related code just as in the example
```
#pragma once
#include <ImNodeFlow.h>

namespace Node_Editor {

    using namespace ImFlow;

    ImNodeFlow* nodeFlow;

    class SimpleSum : public BaseNode
    {
    public:
        SimpleSum()
        {
            setTitle("Simple sum");
            setStyle(NodeStyle::green());
            addIN<int>("IN_VAL", 0, ConnectionFilter_Int);
            addOUT<int>("OUT_VAL", ConnectionFilter_Int)
                ->behaviour([this]() { return getInVal<int>("IN_VAL") + m_valB; });
        }

        void draw() override
        {
            ImGui::SetNextItemWidth(100.f);
            ImGui::InputInt("##ValB", &m_valB);
        }
    private:
        int m_valB = 0;
    };

	void init() {
        nodeFlow = new ImNodeFlow("node Editor");
        nodeFlow->addNode<SimpleSum>(ImVec2(0,0));
        nodeFlow->addNode<SimpleSum>(ImVec2(100, 100));
	}

	void shutdown() {
        delete nodeFlow;
	}

	void Exec() {
        nodeFlow->update();
	}
}
```

**Comment by Fattorino** [comment] 2024-04-02 17:51
That's weird, did you clone the master branch or the latest stable release?

**Comment by Paolo-Oliverio** [comment] 2024-04-03 08:02
tried both

**Comment by Fattorino** [comment] 2024-04-03 09:05
Very strange, I'll look into it today

**Comment by Fattorino** [comment] 2024-04-04 07:49
I cannot reproduce the issue, I suggest you try implementing a basic setup in the demo Imgui project to make sure it's not a problem caused by the "framework" you are using. Also keep in mind to move around the grid, by default the middle_mouse_click must be used

**Comment by Paolo-Oliverio** [comment] 2024-04-04 18:27
I forgot to say it, but moving around also works, but not moving nodes or linking or pressing buttons on them.
I'll try in another project with a different framework I'm actually using kinc and did the imgui port mostly from scratch.
however I use it regularly for other imgui task especially in conjunction with implot where input works well i have also tryed to just run node editor window to exclude some other imgui widgets consume the input.
I'm actually compiling with cpp latest specs in visual studio.

**Comment by Paolo-Oliverio** [comment] 2024-04-07 00:46
in ImNodeFlow::update() I tryed to do auto mousepos = ImGui::GetMousePos(); Kiss::log::info("mouse pos: %f %f", mousepos.x, mousepos.y); // just my  log function
it reports right mouse positions if called before m_context.begin(); and huge negative number if called between your context.

there is something in m_context.begin() that breaks it i need to investigate further.
same for Cursor that I probably don't set properly( I have to check this) as it gives a fixed vector(8 , 27) before context begin and (0,0) after for any mouse movement.

Clicks get captured properly but giving bad mouse pos I cannot interact with nodes as any rect test fails.

**Comment by Fattorino** [comment] 2024-04-07 02:06
What backend do you use? Because I do all my testing with OpenGL

**Comment by Paolo-Oliverio** [comment] 2024-04-11 06:07
my backend uses a common layer for every api so d3d11 12 gl or vulkan don't make any difference for me and all result in the same issue. possibly my backend doesn't implement something required from your library that is indeed optional in the general imgui use. however having isolated mouse position after entering your context as the main cause of the lack of interaction I should be able to make it work. I'll get you updated it I found something weird in your implementation.

**Comment by Paolo-Oliverio** [comment] 2024-04-11 07:02
Fixed it ... it was indeed strange as I never seen it in any backend

    void move(int x, int y, int movement_x, int movement_y)
    {
        auto &io = ImGui::GetIO();
        io.AddMousePosEvent((float)x, (float)y);
        io.MousePos = ImVec2((float)x, (float)y);
    }
    this is my mouse movement.... I just used io.MousePos and with it imgui just works.... then to make it  
work with your library I added io.AddMousePosEvent after io.MousePosition . this made no difference so I removed io.MousePos and this make your library work but no other widget in imgui even moving or resizing windows. so I added io.MousePos again this time after io.MousePos...and it works flawlessly then checked other backends and them uses just one or the other.

**Comment by Paolo-Oliverio** [comment] 2024-04-11 23:15
It depends on my own framework actually on a local repo . I don't update github one since years.I realized it was too much efforts to document and maintain something not so popular even because also it's  dependencies are lacking major documentation.I'll remember to contact you in case I manage to update it in a usable form.

**Comment by Fattorino** [comment] 2024-04-12 07:07
since a solution was found, I'll close this issue for now

**Closed by Fattorino** 2024-04-12 07:07 UTC
Labels: bug
